version: "3"

dotenv: [".env"]

vars:
    WORKSPACE: .
    SESSION: dev
    CONTAINER_NAME: gramine-java-sgx

tasks:
    devcontainer:
        desc: Build, start, and attach to the devcontainer
        cmds:
            - task: devcontainer-build
            - task: devcontainer-up
            - task: devcontainer-attach

    devcontainer-recreate:
        desc: Recreates a devcontainer from scratch to ensure a clean environment
        cmds:
            - task: devcontainer-down
            - task: devcontainer

    devcontainer-build:
        desc: Build the devcontainer image for this workspace
        cmds:
            - devcontainer build --workspace-folder {{.WORKSPACE}}

    devcontainer-up:
        desc: Start (or reuse) the devcontainer for this workspace
        cmds:
            - devcontainer up --workspace-folder {{.WORKSPACE}}

    devcontainer-attach:
        desc: Exec into the devcontainer and start/attach tmux
        cmds:
            - devcontainer exec --workspace-folder {{.WORKSPACE}} bash 

    devcontainer-down:
        desc: Stop and remove the devcontainer for this workspace
        cmds:
            - docker stop {{.CONTAINER_NAME}} || true
            - docker rm -f -v {{.CONTAINER_NAME}} || true
